apiVersion: v1
kind: Service
metadata:
  name: regression-model-service
  namespace: default
  labels:
    app: regression-model
    prometheus: kube-prometheus
spec:
  type: NodePort
  selector:
    app: regression-model
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30080
      name: http